version: '2'
services:
    freelancr-app:
        image: freelancr
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://freelancr-mysql:3306/freelancr?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=freelancr-elasticsearch:9300
        ports:
            - 8080:8080
    freelancr-mysql:
        extends:
            file: mysql.yml
            service: freelancr-mysql
    freelancr-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: freelancr-elasticsearch
